### ISSUE TITLE
[Module]: Disable Low Ram Flag

### ISSUE THREAD

**Issue by sekedus** [Googlers-Repo/gmr#3]
### Update to

https://raw.githubusercontent.com/sekedus/disable-low-ram/main/update.json

### Module ID

disable-low-ram

### Name

Disable Low Ram Flag

### Description

A simple module to disable Low-Ram flag on Android Go devices

### Raw README

https://raw.githubusercontent.com/sekedus/disable-low-ram/main/README.md

**Comment by DerGoogler** [comment]
Your module will be pulled from Magisk Modules Alt Repo
